name: CI - Linux

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Linux ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux GCC, os: ubuntu-latest }
          - { name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        config:
          - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
          - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libfreetype-dev \
          libopenal-dev # Install OpenAL development files

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build ${{ matrix.platform.flags }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config Release
