name: CI - macOS

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: macOS ${{ matrix.config.name }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
          - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install openal-soft  # Install OpenAL using Homebrew
        brew install cmake        # Ensure cmake is installed
        brew install libxrandr    # If needed for your dependencies
        brew install libxcursor   # If needed for your dependencies

    - name: Configure
      run: cmake -B build ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config Release
